### ISSUE TITLE
No UI Tests

### ISSUE THREAD

**Issue by mehmeteminkartal** [yusufozgul/weatherApp#2]
Hi!

I've contacted murat and told him that I liked your projects and codes. For the next step all I want is a simple UI Test :) 

-----
It needs to add a city and enter to details page then assert that tableview is populated (has elements)

Thanks :)

**Comment by yusufozgul** [comment]
Of course, it will be ready after some time.

**Comment by yusufozgul** [comment]
@mehmeteminkartal hi, the UI test has been completed :)
